// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf C++ Version: 6.31.1

#ifndef service_2eproto_2epb_2eh
#define service_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_service_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_service_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_service_2eproto;
}  // extern "C"
enum DetectFaceStatus_Enum : int;
extern const uint32_t DetectFaceStatus_Enum_internal_data_[];
class DetectFaceStatus;
struct DetectFaceStatusDefaultTypeInternal;
extern DetectFaceStatusDefaultTypeInternal _DetectFaceStatus_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DetectFaceStatus_class_data_;
class DetectFacesRequest;
struct DetectFacesRequestDefaultTypeInternal;
extern DetectFacesRequestDefaultTypeInternal _DetectFacesRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DetectFacesRequest_class_data_;
class DetectFacesResponse;
struct DetectFacesResponseDefaultTypeInternal;
extern DetectFacesResponseDefaultTypeInternal _DetectFacesResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DetectFacesResponse_class_data_;
class DetectFacesResponse_Face;
struct DetectFacesResponse_FaceDefaultTypeInternal;
extern DetectFacesResponse_FaceDefaultTypeInternal _DetectFacesResponse_Face_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DetectFacesResponse_Face_class_data_;
class RecognizeFacesRequest;
struct RecognizeFacesRequestDefaultTypeInternal;
extern RecognizeFacesRequestDefaultTypeInternal _RecognizeFacesRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RecognizeFacesRequest_class_data_;
class RecognizeFacesRequest_Face;
struct RecognizeFacesRequest_FaceDefaultTypeInternal;
extern RecognizeFacesRequest_FaceDefaultTypeInternal _RecognizeFacesRequest_Face_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RecognizeFacesRequest_Face_class_data_;
class RecognizeFacesResponse;
struct RecognizeFacesResponseDefaultTypeInternal;
extern RecognizeFacesResponseDefaultTypeInternal _RecognizeFacesResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RecognizeFacesResponse_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::DetectFaceStatus_Enum_internal_data_>
    internal::EnumTraitsImpl::value<::DetectFaceStatus_Enum>;
}  // namespace protobuf
}  // namespace google

enum DetectFaceStatus_Enum : int {
  DetectFaceStatus_Enum_ENUM_UNSPECIFIED = 0,
  DetectFaceStatus_Enum_ENUM_OK = 1,
  DetectFaceStatus_Enum_ENUM_FAILED = 2,
  DetectFaceStatus_Enum_ENUM_NO_FACES = 3,
  DetectFaceStatus_Enum_DetectFaceStatus_Enum_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  DetectFaceStatus_Enum_DetectFaceStatus_Enum_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t DetectFaceStatus_Enum_internal_data_[];
inline constexpr DetectFaceStatus_Enum DetectFaceStatus_Enum_Enum_MIN =
    static_cast<DetectFaceStatus_Enum>(0);
inline constexpr DetectFaceStatus_Enum DetectFaceStatus_Enum_Enum_MAX =
    static_cast<DetectFaceStatus_Enum>(3);
inline bool DetectFaceStatus_Enum_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int DetectFaceStatus_Enum_Enum_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL DetectFaceStatus_Enum_descriptor();
template <typename T>
const ::std::string& DetectFaceStatus_Enum_Name(T value) {
  static_assert(::std::is_same<T, DetectFaceStatus_Enum>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Enum_Name().");
  return DetectFaceStatus_Enum_Name(static_cast<DetectFaceStatus_Enum>(value));
}
template <>
inline const ::std::string& DetectFaceStatus_Enum_Name(DetectFaceStatus_Enum value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DetectFaceStatus_Enum_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool DetectFaceStatus_Enum_Parse(
    ::absl::string_view name, DetectFaceStatus_Enum* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<DetectFaceStatus_Enum>(DetectFaceStatus_Enum_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class RecognizeFacesResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RecognizeFacesResponse) */ {
 public:
  inline RecognizeFacesResponse() : RecognizeFacesResponse(nullptr) {}
  ~RecognizeFacesResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RecognizeFacesResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RecognizeFacesResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RecognizeFacesResponse(::google::protobuf::internal::ConstantInitialized);

  inline RecognizeFacesResponse(const RecognizeFacesResponse& from) : RecognizeFacesResponse(nullptr, from) {}
  inline RecognizeFacesResponse(RecognizeFacesResponse&& from) noexcept
      : RecognizeFacesResponse(nullptr, ::std::move(from)) {}
  inline RecognizeFacesResponse& operator=(const RecognizeFacesResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecognizeFacesResponse& operator=(RecognizeFacesResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecognizeFacesResponse& default_instance() {
    return *reinterpret_cast<const RecognizeFacesResponse*>(
        &_RecognizeFacesResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(RecognizeFacesResponse& a, RecognizeFacesResponse& b) { a.Swap(&b); }
  inline void Swap(RecognizeFacesResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecognizeFacesResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecognizeFacesResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RecognizeFacesResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RecognizeFacesResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RecognizeFacesResponse& from) { RecognizeFacesResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RecognizeFacesResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RecognizeFacesResponse"; }

 protected:
  explicit RecognizeFacesResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RecognizeFacesResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RecognizeFacesResponse& from);
  RecognizeFacesResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RecognizeFacesResponse&& from) noexcept
      : RecognizeFacesResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
    kValidFieldNumber = 2,
  };
  // .DetectFaceStatus.Enum status = 1;
  void clear_status() ;
  ::DetectFaceStatus_Enum status() const;
  void set_status(::DetectFaceStatus_Enum value);

  private:
  ::DetectFaceStatus_Enum _internal_status() const;
  void _internal_set_status(::DetectFaceStatus_Enum value);

  public:
  // bool valid = 2;
  void clear_valid() ;
  bool valid() const;
  void set_valid(bool value);

  private:
  bool _internal_valid() const;
  void _internal_set_valid(bool value);

  public:
  // @@protoc_insertion_point(class_scope:RecognizeFacesResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RecognizeFacesResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int status_;
    bool valid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_service_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RecognizeFacesResponse_class_data_;
// -------------------------------------------------------------------

class RecognizeFacesRequest_Face final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RecognizeFacesRequest.Face) */ {
 public:
  inline RecognizeFacesRequest_Face() : RecognizeFacesRequest_Face(nullptr) {}
  ~RecognizeFacesRequest_Face() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RecognizeFacesRequest_Face* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RecognizeFacesRequest_Face));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RecognizeFacesRequest_Face(::google::protobuf::internal::ConstantInitialized);

  inline RecognizeFacesRequest_Face(const RecognizeFacesRequest_Face& from) : RecognizeFacesRequest_Face(nullptr, from) {}
  inline RecognizeFacesRequest_Face(RecognizeFacesRequest_Face&& from) noexcept
      : RecognizeFacesRequest_Face(nullptr, ::std::move(from)) {}
  inline RecognizeFacesRequest_Face& operator=(const RecognizeFacesRequest_Face& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecognizeFacesRequest_Face& operator=(RecognizeFacesRequest_Face&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecognizeFacesRequest_Face& default_instance() {
    return *reinterpret_cast<const RecognizeFacesRequest_Face*>(
        &_RecognizeFacesRequest_Face_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RecognizeFacesRequest_Face& a, RecognizeFacesRequest_Face& b) { a.Swap(&b); }
  inline void Swap(RecognizeFacesRequest_Face* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecognizeFacesRequest_Face* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecognizeFacesRequest_Face* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RecognizeFacesRequest_Face>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RecognizeFacesRequest_Face& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RecognizeFacesRequest_Face& from) { RecognizeFacesRequest_Face::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RecognizeFacesRequest_Face* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RecognizeFacesRequest.Face"; }

 protected:
  explicit RecognizeFacesRequest_Face(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RecognizeFacesRequest_Face(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RecognizeFacesRequest_Face& from);
  RecognizeFacesRequest_Face(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RecognizeFacesRequest_Face&& from) noexcept
      : RecognizeFacesRequest_Face(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLandmarksFieldNumber = 1,
  };
  // repeated float landmarks = 1;
  int landmarks_size() const;
  private:
  int _internal_landmarks_size() const;

  public:
  void clear_landmarks() ;
  float landmarks(int index) const;
  void set_landmarks(int index, float value);
  void add_landmarks(float value);
  const ::google::protobuf::RepeatedField<float>& landmarks() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_landmarks();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_landmarks() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_landmarks();

  public:
  // @@protoc_insertion_point(class_scope:RecognizeFacesRequest.Face)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RecognizeFacesRequest_Face& from_msg);
    ::google::protobuf::RepeatedField<float> landmarks_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_service_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RecognizeFacesRequest_Face_class_data_;
// -------------------------------------------------------------------

class DetectFacesResponse_Face final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DetectFacesResponse.Face) */ {
 public:
  inline DetectFacesResponse_Face() : DetectFacesResponse_Face(nullptr) {}
  ~DetectFacesResponse_Face() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DetectFacesResponse_Face* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DetectFacesResponse_Face));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DetectFacesResponse_Face(::google::protobuf::internal::ConstantInitialized);

  inline DetectFacesResponse_Face(const DetectFacesResponse_Face& from) : DetectFacesResponse_Face(nullptr, from) {}
  inline DetectFacesResponse_Face(DetectFacesResponse_Face&& from) noexcept
      : DetectFacesResponse_Face(nullptr, ::std::move(from)) {}
  inline DetectFacesResponse_Face& operator=(const DetectFacesResponse_Face& from) {
    CopyFrom(from);
    return *this;
  }
  inline DetectFacesResponse_Face& operator=(DetectFacesResponse_Face&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DetectFacesResponse_Face& default_instance() {
    return *reinterpret_cast<const DetectFacesResponse_Face*>(
        &_DetectFacesResponse_Face_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(DetectFacesResponse_Face& a, DetectFacesResponse_Face& b) { a.Swap(&b); }
  inline void Swap(DetectFacesResponse_Face* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DetectFacesResponse_Face* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DetectFacesResponse_Face* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DetectFacesResponse_Face>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DetectFacesResponse_Face& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DetectFacesResponse_Face& from) { DetectFacesResponse_Face::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DetectFacesResponse_Face* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "DetectFacesResponse.Face"; }

 protected:
  explicit DetectFacesResponse_Face(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DetectFacesResponse_Face(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DetectFacesResponse_Face& from);
  DetectFacesResponse_Face(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DetectFacesResponse_Face&& from) noexcept
      : DetectFacesResponse_Face(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLandmarksFieldNumber = 6,
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kWidthFieldNumber = 3,
    kHeightFieldNumber = 4,
    kConfidenceFieldNumber = 5,
  };
  // repeated float landmarks = 6;
  int landmarks_size() const;
  private:
  int _internal_landmarks_size() const;

  public:
  void clear_landmarks() ;
  float landmarks(int index) const;
  void set_landmarks(int index, float value);
  void add_landmarks(float value);
  const ::google::protobuf::RepeatedField<float>& landmarks() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_landmarks();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_landmarks() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_landmarks();

  public:
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float width = 3;
  void clear_width() ;
  float width() const;
  void set_width(float value);

  private:
  float _internal_width() const;
  void _internal_set_width(float value);

  public:
  // float height = 4;
  void clear_height() ;
  float height() const;
  void set_height(float value);

  private:
  float _internal_height() const;
  void _internal_set_height(float value);

  public:
  // float confidence = 5;
  void clear_confidence() ;
  float confidence() const;
  void set_confidence(float value);

  private:
  float _internal_confidence() const;
  void _internal_set_confidence(float value);

  public:
  // @@protoc_insertion_point(class_scope:DetectFacesResponse.Face)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DetectFacesResponse_Face& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> landmarks_;
    float x_;
    float y_;
    float width_;
    float height_;
    float confidence_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_service_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DetectFacesResponse_Face_class_data_;
// -------------------------------------------------------------------

class DetectFacesRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DetectFacesRequest) */ {
 public:
  inline DetectFacesRequest() : DetectFacesRequest(nullptr) {}
  ~DetectFacesRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DetectFacesRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DetectFacesRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DetectFacesRequest(::google::protobuf::internal::ConstantInitialized);

  inline DetectFacesRequest(const DetectFacesRequest& from) : DetectFacesRequest(nullptr, from) {}
  inline DetectFacesRequest(DetectFacesRequest&& from) noexcept
      : DetectFacesRequest(nullptr, ::std::move(from)) {}
  inline DetectFacesRequest& operator=(const DetectFacesRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DetectFacesRequest& operator=(DetectFacesRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DetectFacesRequest& default_instance() {
    return *reinterpret_cast<const DetectFacesRequest*>(
        &_DetectFacesRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(DetectFacesRequest& a, DetectFacesRequest& b) { a.Swap(&b); }
  inline void Swap(DetectFacesRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DetectFacesRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DetectFacesRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DetectFacesRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DetectFacesRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DetectFacesRequest& from) { DetectFacesRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DetectFacesRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "DetectFacesRequest"; }

 protected:
  explicit DetectFacesRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DetectFacesRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DetectFacesRequest& from);
  DetectFacesRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DetectFacesRequest&& from) noexcept
      : DetectFacesRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kImagesFieldNumber = 1,
  };
  // repeated bytes images = 1;
  int images_size() const;
  private:
  int _internal_images_size() const;

  public:
  void clear_images() ;
  const ::std::string& images(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_images(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_images(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_images();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_images(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& images() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_images();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_images() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_images();

  public:
  // @@protoc_insertion_point(class_scope:DetectFacesRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DetectFacesRequest& from_msg);
    ::google::protobuf::RepeatedPtrField<::std::string> images_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_service_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DetectFacesRequest_class_data_;
// -------------------------------------------------------------------

class DetectFaceStatus final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:DetectFaceStatus) */ {
 public:
  inline DetectFaceStatus() : DetectFaceStatus(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DetectFaceStatus* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DetectFaceStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DetectFaceStatus(::google::protobuf::internal::ConstantInitialized);

  inline DetectFaceStatus(const DetectFaceStatus& from) : DetectFaceStatus(nullptr, from) {}
  inline DetectFaceStatus(DetectFaceStatus&& from) noexcept
      : DetectFaceStatus(nullptr, ::std::move(from)) {}
  inline DetectFaceStatus& operator=(const DetectFaceStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline DetectFaceStatus& operator=(DetectFaceStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DetectFaceStatus& default_instance() {
    return *reinterpret_cast<const DetectFaceStatus*>(
        &_DetectFaceStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(DetectFaceStatus& a, DetectFaceStatus& b) { a.Swap(&b); }
  inline void Swap(DetectFaceStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DetectFaceStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DetectFaceStatus* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<DetectFaceStatus>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const DetectFaceStatus& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const DetectFaceStatus& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "DetectFaceStatus"; }

 protected:
  explicit DetectFaceStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DetectFaceStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DetectFaceStatus& from);
  DetectFaceStatus(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DetectFaceStatus&& from) noexcept
      : DetectFaceStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Enum = DetectFaceStatus_Enum;
  static constexpr Enum ENUM_UNSPECIFIED = DetectFaceStatus_Enum_ENUM_UNSPECIFIED;
  static constexpr Enum ENUM_OK = DetectFaceStatus_Enum_ENUM_OK;
  static constexpr Enum ENUM_FAILED = DetectFaceStatus_Enum_ENUM_FAILED;
  static constexpr Enum ENUM_NO_FACES = DetectFaceStatus_Enum_ENUM_NO_FACES;
  static inline bool Enum_IsValid(int value) {
    return DetectFaceStatus_Enum_IsValid(value);
  }
  static constexpr Enum Enum_MIN = DetectFaceStatus_Enum_Enum_MIN;
  static constexpr Enum Enum_MAX = DetectFaceStatus_Enum_Enum_MAX;
  static constexpr int Enum_ARRAYSIZE = DetectFaceStatus_Enum_Enum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Enum_descriptor() {
    return DetectFaceStatus_Enum_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Enum_Name(T value) {
    return DetectFaceStatus_Enum_Name(value);
  }
  static inline bool Enum_Parse(
      ::absl::string_view name, Enum* PROTOBUF_NONNULL value) {
    return DetectFaceStatus_Enum_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:DetectFaceStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DetectFaceStatus& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_service_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DetectFaceStatus_class_data_;
// -------------------------------------------------------------------

class RecognizeFacesRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RecognizeFacesRequest) */ {
 public:
  inline RecognizeFacesRequest() : RecognizeFacesRequest(nullptr) {}
  ~RecognizeFacesRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RecognizeFacesRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RecognizeFacesRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RecognizeFacesRequest(::google::protobuf::internal::ConstantInitialized);

  inline RecognizeFacesRequest(const RecognizeFacesRequest& from) : RecognizeFacesRequest(nullptr, from) {}
  inline RecognizeFacesRequest(RecognizeFacesRequest&& from) noexcept
      : RecognizeFacesRequest(nullptr, ::std::move(from)) {}
  inline RecognizeFacesRequest& operator=(const RecognizeFacesRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecognizeFacesRequest& operator=(RecognizeFacesRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecognizeFacesRequest& default_instance() {
    return *reinterpret_cast<const RecognizeFacesRequest*>(
        &_RecognizeFacesRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RecognizeFacesRequest& a, RecognizeFacesRequest& b) { a.Swap(&b); }
  inline void Swap(RecognizeFacesRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecognizeFacesRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecognizeFacesRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RecognizeFacesRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RecognizeFacesRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RecognizeFacesRequest& from) { RecognizeFacesRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RecognizeFacesRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RecognizeFacesRequest"; }

 protected:
  explicit RecognizeFacesRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RecognizeFacesRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RecognizeFacesRequest& from);
  RecognizeFacesRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RecognizeFacesRequest&& from) noexcept
      : RecognizeFacesRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Face = RecognizeFacesRequest_Face;

  // accessors -------------------------------------------------------
  enum : int {
    kFacesFieldNumber = 1,
    kImageFieldNumber = 2,
  };
  // repeated .RecognizeFacesRequest.Face faces = 1;
  int faces_size() const;
  private:
  int _internal_faces_size() const;

  public:
  void clear_faces() ;
  ::RecognizeFacesRequest_Face* PROTOBUF_NONNULL mutable_faces(int index);
  ::google::protobuf::RepeatedPtrField<::RecognizeFacesRequest_Face>* PROTOBUF_NONNULL mutable_faces();

  private:
  const ::google::protobuf::RepeatedPtrField<::RecognizeFacesRequest_Face>& _internal_faces() const;
  ::google::protobuf::RepeatedPtrField<::RecognizeFacesRequest_Face>* PROTOBUF_NONNULL _internal_mutable_faces();
  public:
  const ::RecognizeFacesRequest_Face& faces(int index) const;
  ::RecognizeFacesRequest_Face* PROTOBUF_NONNULL add_faces();
  const ::google::protobuf::RepeatedPtrField<::RecognizeFacesRequest_Face>& faces() const;
  // bytes image = 2;
  void clear_image() ;
  const ::std::string& image() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_image(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_image();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_image();
  void set_allocated_image(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_image() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_image(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_image();

  public:
  // @@protoc_insertion_point(class_scope:RecognizeFacesRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RecognizeFacesRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::RecognizeFacesRequest_Face > faces_;
    ::google::protobuf::internal::ArenaStringPtr image_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_service_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RecognizeFacesRequest_class_data_;
// -------------------------------------------------------------------

class DetectFacesResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DetectFacesResponse) */ {
 public:
  inline DetectFacesResponse() : DetectFacesResponse(nullptr) {}
  ~DetectFacesResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DetectFacesResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DetectFacesResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DetectFacesResponse(::google::protobuf::internal::ConstantInitialized);

  inline DetectFacesResponse(const DetectFacesResponse& from) : DetectFacesResponse(nullptr, from) {}
  inline DetectFacesResponse(DetectFacesResponse&& from) noexcept
      : DetectFacesResponse(nullptr, ::std::move(from)) {}
  inline DetectFacesResponse& operator=(const DetectFacesResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DetectFacesResponse& operator=(DetectFacesResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DetectFacesResponse& default_instance() {
    return *reinterpret_cast<const DetectFacesResponse*>(
        &_DetectFacesResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(DetectFacesResponse& a, DetectFacesResponse& b) { a.Swap(&b); }
  inline void Swap(DetectFacesResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DetectFacesResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DetectFacesResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DetectFacesResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DetectFacesResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DetectFacesResponse& from) { DetectFacesResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DetectFacesResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "DetectFacesResponse"; }

 protected:
  explicit DetectFacesResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DetectFacesResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DetectFacesResponse& from);
  DetectFacesResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DetectFacesResponse&& from) noexcept
      : DetectFacesResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Face = DetectFacesResponse_Face;

  // accessors -------------------------------------------------------
  enum : int {
    kFacesFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // repeated .DetectFacesResponse.Face faces = 2;
  int faces_size() const;
  private:
  int _internal_faces_size() const;

  public:
  void clear_faces() ;
  ::DetectFacesResponse_Face* PROTOBUF_NONNULL mutable_faces(int index);
  ::google::protobuf::RepeatedPtrField<::DetectFacesResponse_Face>* PROTOBUF_NONNULL mutable_faces();

  private:
  const ::google::protobuf::RepeatedPtrField<::DetectFacesResponse_Face>& _internal_faces() const;
  ::google::protobuf::RepeatedPtrField<::DetectFacesResponse_Face>* PROTOBUF_NONNULL _internal_mutable_faces();
  public:
  const ::DetectFacesResponse_Face& faces(int index) const;
  ::DetectFacesResponse_Face* PROTOBUF_NONNULL add_faces();
  const ::google::protobuf::RepeatedPtrField<::DetectFacesResponse_Face>& faces() const;
  // .DetectFaceStatus.Enum status = 1;
  void clear_status() ;
  ::DetectFaceStatus_Enum status() const;
  void set_status(::DetectFaceStatus_Enum value);

  private:
  ::DetectFaceStatus_Enum _internal_status() const;
  void _internal_set_status(::DetectFaceStatus_Enum value);

  public:
  // @@protoc_insertion_point(class_scope:DetectFacesResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DetectFacesResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::DetectFacesResponse_Face > faces_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_service_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DetectFacesResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RecognizeFacesRequest_Face

// repeated float landmarks = 1;
inline int RecognizeFacesRequest_Face::_internal_landmarks_size() const {
  return _internal_landmarks().size();
}
inline int RecognizeFacesRequest_Face::landmarks_size() const {
  return _internal_landmarks_size();
}
inline void RecognizeFacesRequest_Face::clear_landmarks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.landmarks_.Clear();
}
inline float RecognizeFacesRequest_Face::landmarks(int index) const {
  // @@protoc_insertion_point(field_get:RecognizeFacesRequest.Face.landmarks)
  return _internal_landmarks().Get(index);
}
inline void RecognizeFacesRequest_Face::set_landmarks(int index, float value) {
  _internal_mutable_landmarks()->Set(index, value);
  // @@protoc_insertion_point(field_set:RecognizeFacesRequest.Face.landmarks)
}
inline void RecognizeFacesRequest_Face::add_landmarks(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_landmarks()->Add(value);
  // @@protoc_insertion_point(field_add:RecognizeFacesRequest.Face.landmarks)
}
inline const ::google::protobuf::RepeatedField<float>& RecognizeFacesRequest_Face::landmarks() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:RecognizeFacesRequest.Face.landmarks)
  return _internal_landmarks();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL RecognizeFacesRequest_Face::mutable_landmarks()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:RecognizeFacesRequest.Face.landmarks)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_landmarks();
}
inline const ::google::protobuf::RepeatedField<float>&
RecognizeFacesRequest_Face::_internal_landmarks() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.landmarks_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
RecognizeFacesRequest_Face::_internal_mutable_landmarks() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.landmarks_;
}

// -------------------------------------------------------------------

// RecognizeFacesRequest

// repeated .RecognizeFacesRequest.Face faces = 1;
inline int RecognizeFacesRequest::_internal_faces_size() const {
  return _internal_faces().size();
}
inline int RecognizeFacesRequest::faces_size() const {
  return _internal_faces_size();
}
inline void RecognizeFacesRequest::clear_faces() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.faces_.Clear();
}
inline ::RecognizeFacesRequest_Face* PROTOBUF_NONNULL RecognizeFacesRequest::mutable_faces(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:RecognizeFacesRequest.faces)
  return _internal_mutable_faces()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::RecognizeFacesRequest_Face>* PROTOBUF_NONNULL RecognizeFacesRequest::mutable_faces()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:RecognizeFacesRequest.faces)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_faces();
}
inline const ::RecognizeFacesRequest_Face& RecognizeFacesRequest::faces(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:RecognizeFacesRequest.faces)
  return _internal_faces().Get(index);
}
inline ::RecognizeFacesRequest_Face* PROTOBUF_NONNULL RecognizeFacesRequest::add_faces()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::RecognizeFacesRequest_Face* _add = _internal_mutable_faces()->Add();
  // @@protoc_insertion_point(field_add:RecognizeFacesRequest.faces)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::RecognizeFacesRequest_Face>& RecognizeFacesRequest::faces() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:RecognizeFacesRequest.faces)
  return _internal_faces();
}
inline const ::google::protobuf::RepeatedPtrField<::RecognizeFacesRequest_Face>&
RecognizeFacesRequest::_internal_faces() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.faces_;
}
inline ::google::protobuf::RepeatedPtrField<::RecognizeFacesRequest_Face>* PROTOBUF_NONNULL
RecognizeFacesRequest::_internal_mutable_faces() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.faces_;
}

// bytes image = 2;
inline void RecognizeFacesRequest::clear_image() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& RecognizeFacesRequest::image() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:RecognizeFacesRequest.image)
  return _internal_image();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RecognizeFacesRequest::set_image(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.image_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:RecognizeFacesRequest.image)
}
inline ::std::string* PROTOBUF_NONNULL RecognizeFacesRequest::mutable_image()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_image();
  // @@protoc_insertion_point(field_mutable:RecognizeFacesRequest.image)
  return _s;
}
inline const ::std::string& RecognizeFacesRequest::_internal_image() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.image_.Get();
}
inline void RecognizeFacesRequest::_internal_set_image(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.image_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RecognizeFacesRequest::_internal_mutable_image() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.image_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RecognizeFacesRequest::release_image() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:RecognizeFacesRequest.image)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.image_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.image_.Set("", GetArena());
  }
  return released;
}
inline void RecognizeFacesRequest::set_allocated_image(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.image_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.image_.IsDefault()) {
    _impl_.image_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:RecognizeFacesRequest.image)
}

// -------------------------------------------------------------------

// RecognizeFacesResponse

// .DetectFaceStatus.Enum status = 1;
inline void RecognizeFacesResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::DetectFaceStatus_Enum RecognizeFacesResponse::status() const {
  // @@protoc_insertion_point(field_get:RecognizeFacesResponse.status)
  return _internal_status();
}
inline void RecognizeFacesResponse::set_status(::DetectFaceStatus_Enum value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:RecognizeFacesResponse.status)
}
inline ::DetectFaceStatus_Enum RecognizeFacesResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::DetectFaceStatus_Enum>(_impl_.status_);
}
inline void RecognizeFacesResponse::_internal_set_status(::DetectFaceStatus_Enum value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// bool valid = 2;
inline void RecognizeFacesResponse::clear_valid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.valid_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool RecognizeFacesResponse::valid() const {
  // @@protoc_insertion_point(field_get:RecognizeFacesResponse.valid)
  return _internal_valid();
}
inline void RecognizeFacesResponse::set_valid(bool value) {
  _internal_set_valid(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:RecognizeFacesResponse.valid)
}
inline bool RecognizeFacesResponse::_internal_valid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.valid_;
}
inline void RecognizeFacesResponse::_internal_set_valid(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.valid_ = value;
}

// -------------------------------------------------------------------

// DetectFacesRequest

// repeated bytes images = 1;
inline int DetectFacesRequest::_internal_images_size() const {
  return _internal_images().size();
}
inline int DetectFacesRequest::images_size() const {
  return _internal_images_size();
}
inline void DetectFacesRequest::clear_images() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.images_.Clear();
}
inline ::std::string* PROTOBUF_NONNULL DetectFacesRequest::add_images()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s = _internal_mutable_images()->Add();
  // @@protoc_insertion_point(field_add_mutable:DetectFacesRequest.images)
  return _s;
}
inline const ::std::string& DetectFacesRequest::images(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DetectFacesRequest.images)
  return _internal_images().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL DetectFacesRequest::mutable_images(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:DetectFacesRequest.images)
  return _internal_mutable_images()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void DetectFacesRequest::set_images(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_images()->Mutable(index), ::std::forward<Arg_>(value),
                        args... , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_set:DetectFacesRequest.images)
}
template <typename Arg_, typename... Args_>
inline void DetectFacesRequest::add_images(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_images(),
                               ::std::forward<Arg_>(value),
                               args... , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_add:DetectFacesRequest.images)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& DetectFacesRequest::images()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:DetectFacesRequest.images)
  return _internal_images();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
DetectFacesRequest::mutable_images() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:DetectFacesRequest.images)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_images();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
DetectFacesRequest::_internal_images() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.images_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
DetectFacesRequest::_internal_mutable_images() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.images_;
}

// -------------------------------------------------------------------

// DetectFacesResponse_Face

// float x = 1;
inline void DetectFacesResponse_Face::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float DetectFacesResponse_Face::x() const {
  // @@protoc_insertion_point(field_get:DetectFacesResponse.Face.x)
  return _internal_x();
}
inline void DetectFacesResponse_Face::set_x(float value) {
  _internal_set_x(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:DetectFacesResponse.Face.x)
}
inline float DetectFacesResponse_Face::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void DetectFacesResponse_Face::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 2;
inline void DetectFacesResponse_Face::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float DetectFacesResponse_Face::y() const {
  // @@protoc_insertion_point(field_get:DetectFacesResponse.Face.y)
  return _internal_y();
}
inline void DetectFacesResponse_Face::set_y(float value) {
  _internal_set_y(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:DetectFacesResponse.Face.y)
}
inline float DetectFacesResponse_Face::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void DetectFacesResponse_Face::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float width = 3;
inline void DetectFacesResponse_Face::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float DetectFacesResponse_Face::width() const {
  // @@protoc_insertion_point(field_get:DetectFacesResponse.Face.width)
  return _internal_width();
}
inline void DetectFacesResponse_Face::set_width(float value) {
  _internal_set_width(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:DetectFacesResponse.Face.width)
}
inline float DetectFacesResponse_Face::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void DetectFacesResponse_Face::_internal_set_width(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// float height = 4;
inline void DetectFacesResponse_Face::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float DetectFacesResponse_Face::height() const {
  // @@protoc_insertion_point(field_get:DetectFacesResponse.Face.height)
  return _internal_height();
}
inline void DetectFacesResponse_Face::set_height(float value) {
  _internal_set_height(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:DetectFacesResponse.Face.height)
}
inline float DetectFacesResponse_Face::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void DetectFacesResponse_Face::_internal_set_height(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// float confidence = 5;
inline void DetectFacesResponse_Face::clear_confidence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.confidence_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline float DetectFacesResponse_Face::confidence() const {
  // @@protoc_insertion_point(field_get:DetectFacesResponse.Face.confidence)
  return _internal_confidence();
}
inline void DetectFacesResponse_Face::set_confidence(float value) {
  _internal_set_confidence(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:DetectFacesResponse.Face.confidence)
}
inline float DetectFacesResponse_Face::_internal_confidence() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.confidence_;
}
inline void DetectFacesResponse_Face::_internal_set_confidence(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.confidence_ = value;
}

// repeated float landmarks = 6;
inline int DetectFacesResponse_Face::_internal_landmarks_size() const {
  return _internal_landmarks().size();
}
inline int DetectFacesResponse_Face::landmarks_size() const {
  return _internal_landmarks_size();
}
inline void DetectFacesResponse_Face::clear_landmarks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.landmarks_.Clear();
}
inline float DetectFacesResponse_Face::landmarks(int index) const {
  // @@protoc_insertion_point(field_get:DetectFacesResponse.Face.landmarks)
  return _internal_landmarks().Get(index);
}
inline void DetectFacesResponse_Face::set_landmarks(int index, float value) {
  _internal_mutable_landmarks()->Set(index, value);
  // @@protoc_insertion_point(field_set:DetectFacesResponse.Face.landmarks)
}
inline void DetectFacesResponse_Face::add_landmarks(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_landmarks()->Add(value);
  // @@protoc_insertion_point(field_add:DetectFacesResponse.Face.landmarks)
}
inline const ::google::protobuf::RepeatedField<float>& DetectFacesResponse_Face::landmarks() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:DetectFacesResponse.Face.landmarks)
  return _internal_landmarks();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL DetectFacesResponse_Face::mutable_landmarks()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:DetectFacesResponse.Face.landmarks)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_landmarks();
}
inline const ::google::protobuf::RepeatedField<float>&
DetectFacesResponse_Face::_internal_landmarks() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.landmarks_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
DetectFacesResponse_Face::_internal_mutable_landmarks() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.landmarks_;
}

// -------------------------------------------------------------------

// DetectFacesResponse

// .DetectFaceStatus.Enum status = 1;
inline void DetectFacesResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::DetectFaceStatus_Enum DetectFacesResponse::status() const {
  // @@protoc_insertion_point(field_get:DetectFacesResponse.status)
  return _internal_status();
}
inline void DetectFacesResponse::set_status(::DetectFaceStatus_Enum value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:DetectFacesResponse.status)
}
inline ::DetectFaceStatus_Enum DetectFacesResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::DetectFaceStatus_Enum>(_impl_.status_);
}
inline void DetectFacesResponse::_internal_set_status(::DetectFaceStatus_Enum value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// repeated .DetectFacesResponse.Face faces = 2;
inline int DetectFacesResponse::_internal_faces_size() const {
  return _internal_faces().size();
}
inline int DetectFacesResponse::faces_size() const {
  return _internal_faces_size();
}
inline void DetectFacesResponse::clear_faces() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.faces_.Clear();
}
inline ::DetectFacesResponse_Face* PROTOBUF_NONNULL DetectFacesResponse::mutable_faces(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:DetectFacesResponse.faces)
  return _internal_mutable_faces()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::DetectFacesResponse_Face>* PROTOBUF_NONNULL DetectFacesResponse::mutable_faces()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:DetectFacesResponse.faces)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_faces();
}
inline const ::DetectFacesResponse_Face& DetectFacesResponse::faces(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DetectFacesResponse.faces)
  return _internal_faces().Get(index);
}
inline ::DetectFacesResponse_Face* PROTOBUF_NONNULL DetectFacesResponse::add_faces()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::DetectFacesResponse_Face* _add = _internal_mutable_faces()->Add();
  // @@protoc_insertion_point(field_add:DetectFacesResponse.faces)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::DetectFacesResponse_Face>& DetectFacesResponse::faces() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:DetectFacesResponse.faces)
  return _internal_faces();
}
inline const ::google::protobuf::RepeatedPtrField<::DetectFacesResponse_Face>&
DetectFacesResponse::_internal_faces() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.faces_;
}
inline ::google::protobuf::RepeatedPtrField<::DetectFacesResponse_Face>* PROTOBUF_NONNULL
DetectFacesResponse::_internal_mutable_faces() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.faces_;
}

// -------------------------------------------------------------------

// DetectFaceStatus

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::DetectFaceStatus_Enum> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::DetectFaceStatus_Enum>() {
  return ::DetectFaceStatus_Enum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // service_2eproto_2epb_2eh
