// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf C++ Version: 6.31.1

#include "service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr RecognizeFacesResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        status_{static_cast< ::DetectFaceStatus_Enum >(0)},
        valid_{false} {}

template <typename>
PROTOBUF_CONSTEXPR RecognizeFacesResponse::RecognizeFacesResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RecognizeFacesResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RecognizeFacesResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecognizeFacesResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecognizeFacesResponseDefaultTypeInternal() {}
  union {
    RecognizeFacesResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecognizeFacesResponseDefaultTypeInternal _RecognizeFacesResponse_default_instance_;

inline constexpr RecognizeFacesRequest_Face::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : landmarks_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RecognizeFacesRequest_Face::RecognizeFacesRequest_Face(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RecognizeFacesRequest_Face_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RecognizeFacesRequest_FaceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecognizeFacesRequest_FaceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecognizeFacesRequest_FaceDefaultTypeInternal() {}
  union {
    RecognizeFacesRequest_Face _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecognizeFacesRequest_FaceDefaultTypeInternal _RecognizeFacesRequest_Face_default_instance_;

inline constexpr DetectFacesResponse_Face::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        landmarks_{},
        x_{0},
        y_{0},
        width_{0},
        height_{0},
        confidence_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DetectFacesResponse_Face::DetectFacesResponse_Face(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(DetectFacesResponse_Face_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DetectFacesResponse_FaceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DetectFacesResponse_FaceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DetectFacesResponse_FaceDefaultTypeInternal() {}
  union {
    DetectFacesResponse_Face _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DetectFacesResponse_FaceDefaultTypeInternal _DetectFacesResponse_Face_default_instance_;

inline constexpr DetectFacesRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : images_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DetectFacesRequest::DetectFacesRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(DetectFacesRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DetectFacesRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DetectFacesRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DetectFacesRequestDefaultTypeInternal() {}
  union {
    DetectFacesRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DetectFacesRequestDefaultTypeInternal _DetectFacesRequest_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR DetectFaceStatus::DetectFaceStatus(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(DetectFaceStatus_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct DetectFaceStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DetectFaceStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DetectFaceStatusDefaultTypeInternal() {}
  union {
    DetectFaceStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DetectFaceStatusDefaultTypeInternal _DetectFaceStatus_default_instance_;

inline constexpr RecognizeFacesRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        faces_{},
        image_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RecognizeFacesRequest::RecognizeFacesRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RecognizeFacesRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RecognizeFacesRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecognizeFacesRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecognizeFacesRequestDefaultTypeInternal() {}
  union {
    RecognizeFacesRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecognizeFacesRequestDefaultTypeInternal _RecognizeFacesRequest_default_instance_;

inline constexpr DetectFacesResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        faces_{},
        status_{static_cast< ::DetectFaceStatus_Enum >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR DetectFacesResponse::DetectFacesResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(DetectFacesResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DetectFacesResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DetectFacesResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DetectFacesResponseDefaultTypeInternal() {}
  union {
    DetectFacesResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DetectFacesResponseDefaultTypeInternal _DetectFacesResponse_default_instance_;
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_service_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_service_2eproto = nullptr;
const ::uint32_t
    TableStruct_service_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::RecognizeFacesRequest_Face, _impl_.landmarks_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::RecognizeFacesRequest, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::RecognizeFacesRequest, _impl_.faces_),
        PROTOBUF_FIELD_OFFSET(::RecognizeFacesRequest, _impl_.image_),
        ~0u,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::RecognizeFacesResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::RecognizeFacesResponse, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::RecognizeFacesResponse, _impl_.valid_),
        0,
        1,
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::DetectFacesRequest, _impl_.images_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::DetectFacesResponse_Face, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::DetectFacesResponse_Face, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::DetectFacesResponse_Face, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::DetectFacesResponse_Face, _impl_.width_),
        PROTOBUF_FIELD_OFFSET(::DetectFacesResponse_Face, _impl_.height_),
        PROTOBUF_FIELD_OFFSET(::DetectFacesResponse_Face, _impl_.confidence_),
        PROTOBUF_FIELD_OFFSET(::DetectFacesResponse_Face, _impl_.landmarks_),
        0,
        1,
        2,
        3,
        4,
        ~0u,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::DetectFacesResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::DetectFacesResponse, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::DetectFacesResponse, _impl_.faces_),
        0,
        ~0u,
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::RecognizeFacesRequest_Face)},
        {2, sizeof(::RecognizeFacesRequest)},
        {9, sizeof(::RecognizeFacesResponse)},
        {16, sizeof(::DetectFacesRequest)},
        {18, sizeof(::DetectFacesResponse_Face)},
        {33, sizeof(::DetectFacesResponse)},
        {40, sizeof(::DetectFaceStatus)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_RecognizeFacesRequest_Face_default_instance_._instance,
    &::_RecognizeFacesRequest_default_instance_._instance,
    &::_RecognizeFacesResponse_default_instance_._instance,
    &::_DetectFacesRequest_default_instance_._instance,
    &::_DetectFacesResponse_Face_default_instance_._instance,
    &::_DetectFacesResponse_default_instance_._instance,
    &::_DetectFaceStatus_default_instance_._instance,
};
const char descriptor_table_protodef_service_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rservice.proto\"m\n\025RecognizeFacesRequest"
    "\022*\n\005faces\030\001 \003(\0132\033.RecognizeFacesRequest."
    "Face\022\r\n\005image\030\002 \001(\014\032\031\n\004Face\022\021\n\tlandmarks"
    "\030\001 \003(\002\"O\n\026RecognizeFacesResponse\022&\n\006stat"
    "us\030\001 \001(\0162\026.DetectFaceStatus.Enum\022\r\n\005vali"
    "d\030\002 \001(\010\"$\n\022DetectFacesRequest\022\016\n\006images\030"
    "\001 \003(\014\"\313\001\n\023DetectFacesResponse\022&\n\006status\030"
    "\001 \001(\0162\026.DetectFaceStatus.Enum\022(\n\005faces\030\002"
    " \003(\0132\031.DetectFacesResponse.Face\032b\n\004Face\022"
    "\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\r\n\005width\030\003 \001(\002\022\016\n\006"
    "height\030\004 \001(\002\022\022\n\nconfidence\030\005 \001(\002\022\021\n\tland"
    "marks\030\006 \003(\002\"t\n\020DetectFaceStatus\"`\n\004Enum\022"
    "\024\n\020ENUM_UNSPECIFIED\020\000\022\013\n\007ENUM_OK\020\001\022\017\n\013EN"
    "UM_FAILED\020\002\022\021\n\rENUM_NO_FACES\020\003\022\021\n\rENUM_N"
    "O_MATCH\020\0042\225\001\n\026FaceRecognitionService\0228\n\013"
    "DetectFaces\022\023.DetectFacesRequest\032\024.Detec"
    "tFacesResponse\022A\n\016RecognizeFaces\022\026.Recog"
    "nizeFacesRequest\032\027.RecognizeFacesRespons"
    "eB\016Z\014/client;mainb\006proto3"
};
static ::absl::once_flag descriptor_table_service_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_service_2eproto = {
    false,
    false,
    745,
    descriptor_table_protodef_service_2eproto,
    "service.proto",
    &descriptor_table_service_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_default_instances,
    TableStruct_service_2eproto::offsets,
    file_level_enum_descriptors_service_2eproto,
    file_level_service_descriptors_service_2eproto,
};
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL DetectFaceStatus_Enum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_service_2eproto);
  return file_level_enum_descriptors_service_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t DetectFaceStatus_Enum_internal_data_[] = {
    327680u, 0u, };
// ===================================================================

class RecognizeFacesRequest_Face::_Internal {
 public:
};

RecognizeFacesRequest_Face::RecognizeFacesRequest_Face(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RecognizeFacesRequest_Face_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RecognizeFacesRequest.Face)
}
PROTOBUF_NDEBUG_INLINE RecognizeFacesRequest_Face::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::RecognizeFacesRequest_Face& from_msg)
      : landmarks_{visibility, arena, from.landmarks_},
        _cached_size_{0} {}

RecognizeFacesRequest_Face::RecognizeFacesRequest_Face(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RecognizeFacesRequest_Face& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RecognizeFacesRequest_Face_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RecognizeFacesRequest_Face* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:RecognizeFacesRequest.Face)
}
PROTOBUF_NDEBUG_INLINE RecognizeFacesRequest_Face::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : landmarks_{visibility, arena},
        _cached_size_{0} {}

inline void RecognizeFacesRequest_Face::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RecognizeFacesRequest_Face::~RecognizeFacesRequest_Face() {
  // @@protoc_insertion_point(destructor:RecognizeFacesRequest.Face)
  SharedDtor(*this);
}
inline void RecognizeFacesRequest_Face::SharedDtor(MessageLite& self) {
  RecognizeFacesRequest_Face& this_ = static_cast<RecognizeFacesRequest_Face&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RecognizeFacesRequest_Face::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RecognizeFacesRequest_Face(arena);
}
constexpr auto RecognizeFacesRequest_Face::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest_Face, _impl_.landmarks_) +
          decltype(RecognizeFacesRequest_Face::_impl_.landmarks_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(RecognizeFacesRequest_Face), alignof(RecognizeFacesRequest_Face), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&RecognizeFacesRequest_Face::PlacementNew_,
                                 sizeof(RecognizeFacesRequest_Face),
                                 alignof(RecognizeFacesRequest_Face));
  }
}
constexpr auto RecognizeFacesRequest_Face::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RecognizeFacesRequest_Face_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RecognizeFacesRequest_Face::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RecognizeFacesRequest_Face>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RecognizeFacesRequest_Face::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RecognizeFacesRequest_Face>(), &RecognizeFacesRequest_Face::ByteSizeLong,
              &RecognizeFacesRequest_Face::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest_Face, _impl_._cached_size_),
          false,
      },
      &RecognizeFacesRequest_Face::kDescriptorMethods,
      &descriptor_table_service_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RecognizeFacesRequest_Face_class_data_ =
        RecognizeFacesRequest_Face::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RecognizeFacesRequest_Face::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RecognizeFacesRequest_Face_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RecognizeFacesRequest_Face_class_data_.tc_table);
  return RecognizeFacesRequest_Face_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
RecognizeFacesRequest_Face::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RecognizeFacesRequest_Face_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::RecognizeFacesRequest_Face>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float landmarks = 1;
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest_Face, _impl_.landmarks_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float landmarks = 1;
    {PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest_Face, _impl_.landmarks_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void RecognizeFacesRequest_Face::Clear() {
// @@protoc_insertion_point(message_clear_start:RecognizeFacesRequest.Face)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.landmarks_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RecognizeFacesRequest_Face::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RecognizeFacesRequest_Face& this_ = static_cast<const RecognizeFacesRequest_Face&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RecognizeFacesRequest_Face::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RecognizeFacesRequest_Face& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:RecognizeFacesRequest.Face)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated float landmarks = 1;
  if (this_._internal_landmarks_size() > 0) {
    target = stream->WriteFixedPacked(1, this_._internal_landmarks(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RecognizeFacesRequest.Face)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RecognizeFacesRequest_Face::ByteSizeLong(const MessageLite& base) {
  const RecognizeFacesRequest_Face& this_ = static_cast<const RecognizeFacesRequest_Face&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RecognizeFacesRequest_Face::ByteSizeLong() const {
  const RecognizeFacesRequest_Face& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:RecognizeFacesRequest.Face)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated float landmarks = 1;
    {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_landmarks_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RecognizeFacesRequest_Face::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RecognizeFacesRequest_Face*>(&to_msg);
  auto& from = static_cast<const RecognizeFacesRequest_Face&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RecognizeFacesRequest.Face)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_landmarks()->MergeFrom(from._internal_landmarks());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RecognizeFacesRequest_Face::CopyFrom(const RecognizeFacesRequest_Face& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RecognizeFacesRequest.Face)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RecognizeFacesRequest_Face::InternalSwap(RecognizeFacesRequest_Face* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.landmarks_.InternalSwap(&other->_impl_.landmarks_);
}

::google::protobuf::Metadata RecognizeFacesRequest_Face::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RecognizeFacesRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RecognizeFacesRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest, _impl_._has_bits_);
};

RecognizeFacesRequest::RecognizeFacesRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RecognizeFacesRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RecognizeFacesRequest)
}
PROTOBUF_NDEBUG_INLINE RecognizeFacesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::RecognizeFacesRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        faces_{visibility, arena, from.faces_},
        image_(arena, from.image_) {}

RecognizeFacesRequest::RecognizeFacesRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RecognizeFacesRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RecognizeFacesRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RecognizeFacesRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:RecognizeFacesRequest)
}
PROTOBUF_NDEBUG_INLINE RecognizeFacesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        faces_{visibility, arena},
        image_(arena) {}

inline void RecognizeFacesRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RecognizeFacesRequest::~RecognizeFacesRequest() {
  // @@protoc_insertion_point(destructor:RecognizeFacesRequest)
  SharedDtor(*this);
}
inline void RecognizeFacesRequest::SharedDtor(MessageLite& self) {
  RecognizeFacesRequest& this_ = static_cast<RecognizeFacesRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.image_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RecognizeFacesRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RecognizeFacesRequest(arena);
}
constexpr auto RecognizeFacesRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest, _impl_.faces_) +
          decltype(RecognizeFacesRequest::_impl_.faces_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(RecognizeFacesRequest), alignof(RecognizeFacesRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&RecognizeFacesRequest::PlacementNew_,
                                 sizeof(RecognizeFacesRequest),
                                 alignof(RecognizeFacesRequest));
  }
}
constexpr auto RecognizeFacesRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RecognizeFacesRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RecognizeFacesRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RecognizeFacesRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RecognizeFacesRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RecognizeFacesRequest>(), &RecognizeFacesRequest::ByteSizeLong,
              &RecognizeFacesRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest, _impl_._cached_size_),
          false,
      },
      &RecognizeFacesRequest::kDescriptorMethods,
      &descriptor_table_service_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RecognizeFacesRequest_class_data_ =
        RecognizeFacesRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RecognizeFacesRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RecognizeFacesRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RecognizeFacesRequest_class_data_.tc_table);
  return RecognizeFacesRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
RecognizeFacesRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    RecognizeFacesRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::RecognizeFacesRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes image = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest, _impl_.image_)}},
    // repeated .RecognizeFacesRequest.Face faces = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest, _impl_.faces_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .RecognizeFacesRequest.Face faces = 1;
    {PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest, _impl_.faces_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes image = 2;
    {PROTOBUF_FIELD_OFFSET(RecognizeFacesRequest, _impl_.image_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::RecognizeFacesRequest_Face>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void RecognizeFacesRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:RecognizeFacesRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.faces_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.image_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RecognizeFacesRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RecognizeFacesRequest& this_ = static_cast<const RecognizeFacesRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RecognizeFacesRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RecognizeFacesRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:RecognizeFacesRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .RecognizeFacesRequest.Face faces = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_faces_size());
       i < n; i++) {
    const auto& repfield = this_._internal_faces().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // bytes image = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_image().empty()) {
      const ::std::string& _s = this_._internal_image();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RecognizeFacesRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RecognizeFacesRequest::ByteSizeLong(const MessageLite& base) {
  const RecognizeFacesRequest& this_ = static_cast<const RecognizeFacesRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RecognizeFacesRequest::ByteSizeLong() const {
  const RecognizeFacesRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:RecognizeFacesRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .RecognizeFacesRequest.Face faces = 1;
    {
      total_size += 1UL * this_._internal_faces_size();
      for (const auto& msg : this_._internal_faces()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
   {
    // bytes image = 2;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_image().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_image());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RecognizeFacesRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RecognizeFacesRequest*>(&to_msg);
  auto& from = static_cast<const RecognizeFacesRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RecognizeFacesRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_faces()->MergeFrom(
      from._internal_faces());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_image().empty()) {
      _this->_internal_set_image(from._internal_image());
    } else {
      if (_this->_impl_.image_.IsDefault()) {
        _this->_internal_set_image("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RecognizeFacesRequest::CopyFrom(const RecognizeFacesRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RecognizeFacesRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RecognizeFacesRequest::InternalSwap(RecognizeFacesRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.faces_.InternalSwap(&other->_impl_.faces_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_, &other->_impl_.image_, arena);
}

::google::protobuf::Metadata RecognizeFacesRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RecognizeFacesResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RecognizeFacesResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RecognizeFacesResponse, _impl_._has_bits_);
};

RecognizeFacesResponse::RecognizeFacesResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RecognizeFacesResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RecognizeFacesResponse)
}
RecognizeFacesResponse::RecognizeFacesResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RecognizeFacesResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RecognizeFacesResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE RecognizeFacesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void RecognizeFacesResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           0,
           offsetof(Impl_, valid_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::valid_));
}
RecognizeFacesResponse::~RecognizeFacesResponse() {
  // @@protoc_insertion_point(destructor:RecognizeFacesResponse)
  SharedDtor(*this);
}
inline void RecognizeFacesResponse::SharedDtor(MessageLite& self) {
  RecognizeFacesResponse& this_ = static_cast<RecognizeFacesResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RecognizeFacesResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RecognizeFacesResponse(arena);
}
constexpr auto RecognizeFacesResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RecognizeFacesResponse),
                                            alignof(RecognizeFacesResponse));
}
constexpr auto RecognizeFacesResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RecognizeFacesResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RecognizeFacesResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RecognizeFacesResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RecognizeFacesResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RecognizeFacesResponse>(), &RecognizeFacesResponse::ByteSizeLong,
              &RecognizeFacesResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RecognizeFacesResponse, _impl_._cached_size_),
          false,
      },
      &RecognizeFacesResponse::kDescriptorMethods,
      &descriptor_table_service_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RecognizeFacesResponse_class_data_ =
        RecognizeFacesResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RecognizeFacesResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RecognizeFacesResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RecognizeFacesResponse_class_data_.tc_table);
  return RecognizeFacesResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
RecognizeFacesResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RecognizeFacesResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RecognizeFacesResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::RecognizeFacesResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool valid = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RecognizeFacesResponse, _impl_.valid_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(RecognizeFacesResponse, _impl_.valid_)}},
    // .DetectFaceStatus.Enum status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RecognizeFacesResponse, _impl_.status_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(RecognizeFacesResponse, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .DetectFaceStatus.Enum status = 1;
    {PROTOBUF_FIELD_OFFSET(RecognizeFacesResponse, _impl_.status_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // bool valid = 2;
    {PROTOBUF_FIELD_OFFSET(RecognizeFacesResponse, _impl_.valid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void RecognizeFacesResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:RecognizeFacesResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    ::memset(&_impl_.status_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.valid_) -
        reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.valid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RecognizeFacesResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RecognizeFacesResponse& this_ = static_cast<const RecognizeFacesResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RecognizeFacesResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RecognizeFacesResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:RecognizeFacesResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .DetectFaceStatus.Enum status = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_status(), target);
    }
  }

  // bool valid = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_valid() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this_._internal_valid(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RecognizeFacesResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RecognizeFacesResponse::ByteSizeLong(const MessageLite& base) {
  const RecognizeFacesResponse& this_ = static_cast<const RecognizeFacesResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RecognizeFacesResponse::ByteSizeLong() const {
  const RecognizeFacesResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:RecognizeFacesResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // .DetectFaceStatus.Enum status = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
    // bool valid = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_valid() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RecognizeFacesResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RecognizeFacesResponse*>(&to_msg);
  auto& from = static_cast<const RecognizeFacesResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RecognizeFacesResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_valid() != 0) {
        _this->_impl_.valid_ = from._impl_.valid_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RecognizeFacesResponse::CopyFrom(const RecognizeFacesResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RecognizeFacesResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RecognizeFacesResponse::InternalSwap(RecognizeFacesResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RecognizeFacesResponse, _impl_.valid_)
      + sizeof(RecognizeFacesResponse::_impl_.valid_)
      - PROTOBUF_FIELD_OFFSET(RecognizeFacesResponse, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::google::protobuf::Metadata RecognizeFacesResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DetectFacesRequest::_Internal {
 public:
};

DetectFacesRequest::DetectFacesRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DetectFacesRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DetectFacesRequest)
}
PROTOBUF_NDEBUG_INLINE DetectFacesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::DetectFacesRequest& from_msg)
      : images_{visibility, arena, from.images_},
        _cached_size_{0} {}

DetectFacesRequest::DetectFacesRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DetectFacesRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DetectFacesRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DetectFacesRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:DetectFacesRequest)
}
PROTOBUF_NDEBUG_INLINE DetectFacesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : images_{visibility, arena},
        _cached_size_{0} {}

inline void DetectFacesRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DetectFacesRequest::~DetectFacesRequest() {
  // @@protoc_insertion_point(destructor:DetectFacesRequest)
  SharedDtor(*this);
}
inline void DetectFacesRequest::SharedDtor(MessageLite& self) {
  DetectFacesRequest& this_ = static_cast<DetectFacesRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL DetectFacesRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DetectFacesRequest(arena);
}
constexpr auto DetectFacesRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(DetectFacesRequest, _impl_.images_) +
          decltype(DetectFacesRequest::_impl_.images_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(DetectFacesRequest), alignof(DetectFacesRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&DetectFacesRequest::PlacementNew_,
                                 sizeof(DetectFacesRequest),
                                 alignof(DetectFacesRequest));
  }
}
constexpr auto DetectFacesRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_DetectFacesRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DetectFacesRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<DetectFacesRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DetectFacesRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<DetectFacesRequest>(), &DetectFacesRequest::ByteSizeLong,
              &DetectFacesRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DetectFacesRequest, _impl_._cached_size_),
          false,
      },
      &DetectFacesRequest::kDescriptorMethods,
      &descriptor_table_service_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull DetectFacesRequest_class_data_ =
        DetectFacesRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
DetectFacesRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&DetectFacesRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(DetectFacesRequest_class_data_.tc_table);
  return DetectFacesRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
DetectFacesRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    DetectFacesRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DetectFacesRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated bytes images = 1;
    {::_pbi::TcParser::FastBR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DetectFacesRequest, _impl_.images_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated bytes images = 1;
    {PROTOBUF_FIELD_OFFSET(DetectFacesRequest, _impl_.images_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void DetectFacesRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:DetectFacesRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.images_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DetectFacesRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DetectFacesRequest& this_ = static_cast<const DetectFacesRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DetectFacesRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DetectFacesRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:DetectFacesRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated bytes images = 1;
  for (int i = 0, n = this_._internal_images_size(); i < n; ++i) {
    const auto& s = this_._internal_images().Get(i);
    target = stream->WriteBytes(1, s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DetectFacesRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DetectFacesRequest::ByteSizeLong(const MessageLite& base) {
  const DetectFacesRequest& this_ = static_cast<const DetectFacesRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DetectFacesRequest::ByteSizeLong() const {
  const DetectFacesRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:DetectFacesRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated bytes images = 1;
    {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_images().size());
      for (int i = 0, n = this_._internal_images().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
            this_._internal_images().Get(i));
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void DetectFacesRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DetectFacesRequest*>(&to_msg);
  auto& from = static_cast<const DetectFacesRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DetectFacesRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_images()->MergeFrom(from._internal_images());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DetectFacesRequest::CopyFrom(const DetectFacesRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DetectFacesRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DetectFacesRequest::InternalSwap(DetectFacesRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.images_.InternalSwap(&other->_impl_.images_);
}

::google::protobuf::Metadata DetectFacesRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DetectFacesResponse_Face::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<DetectFacesResponse_Face>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_._has_bits_);
};

DetectFacesResponse_Face::DetectFacesResponse_Face(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DetectFacesResponse_Face_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DetectFacesResponse.Face)
}
PROTOBUF_NDEBUG_INLINE DetectFacesResponse_Face::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::DetectFacesResponse_Face& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        landmarks_{visibility, arena, from.landmarks_} {}

DetectFacesResponse_Face::DetectFacesResponse_Face(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DetectFacesResponse_Face& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DetectFacesResponse_Face_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DetectFacesResponse_Face* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, x_),
           offsetof(Impl_, confidence_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::confidence_));

  // @@protoc_insertion_point(copy_constructor:DetectFacesResponse.Face)
}
PROTOBUF_NDEBUG_INLINE DetectFacesResponse_Face::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        landmarks_{visibility, arena} {}

inline void DetectFacesResponse_Face::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, confidence_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::confidence_));
}
DetectFacesResponse_Face::~DetectFacesResponse_Face() {
  // @@protoc_insertion_point(destructor:DetectFacesResponse.Face)
  SharedDtor(*this);
}
inline void DetectFacesResponse_Face::SharedDtor(MessageLite& self) {
  DetectFacesResponse_Face& this_ = static_cast<DetectFacesResponse_Face&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL DetectFacesResponse_Face::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DetectFacesResponse_Face(arena);
}
constexpr auto DetectFacesResponse_Face::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.landmarks_) +
          decltype(DetectFacesResponse_Face::_impl_.landmarks_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(DetectFacesResponse_Face), alignof(DetectFacesResponse_Face), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&DetectFacesResponse_Face::PlacementNew_,
                                 sizeof(DetectFacesResponse_Face),
                                 alignof(DetectFacesResponse_Face));
  }
}
constexpr auto DetectFacesResponse_Face::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_DetectFacesResponse_Face_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DetectFacesResponse_Face::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<DetectFacesResponse_Face>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DetectFacesResponse_Face::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<DetectFacesResponse_Face>(), &DetectFacesResponse_Face::ByteSizeLong,
              &DetectFacesResponse_Face::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_._cached_size_),
          false,
      },
      &DetectFacesResponse_Face::kDescriptorMethods,
      &descriptor_table_service_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull DetectFacesResponse_Face_class_data_ =
        DetectFacesResponse_Face::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
DetectFacesResponse_Face::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&DetectFacesResponse_Face_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(DetectFacesResponse_Face_class_data_.tc_table);
  return DetectFacesResponse_Face_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 0, 2>
DetectFacesResponse_Face::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    DetectFacesResponse_Face_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DetectFacesResponse_Face>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // float x = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 0, 0, PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.x_)}},
    // float y = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0, PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.y_)}},
    // float width = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.width_)}},
    // float height = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0, PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.height_)}},
    // float confidence = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 4, 0, PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.confidence_)}},
    // repeated float landmarks = 6;
    {::_pbi::TcParser::FastF32P1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.landmarks_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // float x = 1;
    {PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.x_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float y = 2;
    {PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.y_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float width = 3;
    {PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.width_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float height = 4;
    {PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.height_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float confidence = 5;
    {PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.confidence_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // repeated float landmarks = 6;
    {PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.landmarks_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void DetectFacesResponse_Face::Clear() {
// @@protoc_insertion_point(message_clear_start:DetectFacesResponse.Face)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.landmarks_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    ::memset(&_impl_.x_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.confidence_) -
        reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.confidence_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DetectFacesResponse_Face::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DetectFacesResponse_Face& this_ = static_cast<const DetectFacesResponse_Face&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DetectFacesResponse_Face::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DetectFacesResponse_Face& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:DetectFacesResponse.Face)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // float x = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          1, this_._internal_x(), target);
    }
  }

  // float y = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_y(), target);
    }
  }

  // float width = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_width()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          3, this_._internal_width(), target);
    }
  }

  // float height = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_height()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          4, this_._internal_height(), target);
    }
  }

  // float confidence = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_confidence()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          5, this_._internal_confidence(), target);
    }
  }

  // repeated float landmarks = 6;
  if (this_._internal_landmarks_size() > 0) {
    target = stream->WriteFixedPacked(6, this_._internal_landmarks(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DetectFacesResponse.Face)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DetectFacesResponse_Face::ByteSizeLong(const MessageLite& base) {
  const DetectFacesResponse_Face& this_ = static_cast<const DetectFacesResponse_Face&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DetectFacesResponse_Face::ByteSizeLong() const {
  const DetectFacesResponse_Face& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:DetectFacesResponse.Face)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated float landmarks = 6;
    {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_landmarks_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    // float x = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
        total_size += 5;
      }
    }
    // float y = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
        total_size += 5;
      }
    }
    // float width = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_width()) != 0) {
        total_size += 5;
      }
    }
    // float height = 4;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_height()) != 0) {
        total_size += 5;
      }
    }
    // float confidence = 5;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_confidence()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void DetectFacesResponse_Face::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DetectFacesResponse_Face*>(&to_msg);
  auto& from = static_cast<const DetectFacesResponse_Face&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DetectFacesResponse.Face)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_landmarks()->MergeFrom(from._internal_landmarks());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_x()) != 0) {
        _this->_impl_.x_ = from._impl_.x_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_y()) != 0) {
        _this->_impl_.y_ = from._impl_.y_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_width()) != 0) {
        _this->_impl_.width_ = from._impl_.width_;
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_height()) != 0) {
        _this->_impl_.height_ = from._impl_.height_;
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_confidence()) != 0) {
        _this->_impl_.confidence_ = from._impl_.confidence_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DetectFacesResponse_Face::CopyFrom(const DetectFacesResponse_Face& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DetectFacesResponse.Face)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DetectFacesResponse_Face::InternalSwap(DetectFacesResponse_Face* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.landmarks_.InternalSwap(&other->_impl_.landmarks_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.confidence_)
      + sizeof(DetectFacesResponse_Face::_impl_.confidence_)
      - PROTOBUF_FIELD_OFFSET(DetectFacesResponse_Face, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata DetectFacesResponse_Face::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DetectFacesResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<DetectFacesResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DetectFacesResponse, _impl_._has_bits_);
};

DetectFacesResponse::DetectFacesResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DetectFacesResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DetectFacesResponse)
}
PROTOBUF_NDEBUG_INLINE DetectFacesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::DetectFacesResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        faces_{visibility, arena, from.faces_} {}

DetectFacesResponse::DetectFacesResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DetectFacesResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DetectFacesResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DetectFacesResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:DetectFacesResponse)
}
PROTOBUF_NDEBUG_INLINE DetectFacesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        faces_{visibility, arena} {}

inline void DetectFacesResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
DetectFacesResponse::~DetectFacesResponse() {
  // @@protoc_insertion_point(destructor:DetectFacesResponse)
  SharedDtor(*this);
}
inline void DetectFacesResponse::SharedDtor(MessageLite& self) {
  DetectFacesResponse& this_ = static_cast<DetectFacesResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL DetectFacesResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DetectFacesResponse(arena);
}
constexpr auto DetectFacesResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(DetectFacesResponse, _impl_.faces_) +
          decltype(DetectFacesResponse::_impl_.faces_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(DetectFacesResponse), alignof(DetectFacesResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&DetectFacesResponse::PlacementNew_,
                                 sizeof(DetectFacesResponse),
                                 alignof(DetectFacesResponse));
  }
}
constexpr auto DetectFacesResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_DetectFacesResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DetectFacesResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<DetectFacesResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DetectFacesResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<DetectFacesResponse>(), &DetectFacesResponse::ByteSizeLong,
              &DetectFacesResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DetectFacesResponse, _impl_._cached_size_),
          false,
      },
      &DetectFacesResponse::kDescriptorMethods,
      &descriptor_table_service_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull DetectFacesResponse_class_data_ =
        DetectFacesResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
DetectFacesResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&DetectFacesResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(DetectFacesResponse_class_data_.tc_table);
  return DetectFacesResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
DetectFacesResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DetectFacesResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    DetectFacesResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DetectFacesResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .DetectFacesResponse.Face faces = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DetectFacesResponse, _impl_.faces_)}},
    // .DetectFaceStatus.Enum status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DetectFacesResponse, _impl_.status_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(DetectFacesResponse, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .DetectFaceStatus.Enum status = 1;
    {PROTOBUF_FIELD_OFFSET(DetectFacesResponse, _impl_.status_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // repeated .DetectFacesResponse.Face faces = 2;
    {PROTOBUF_FIELD_OFFSET(DetectFacesResponse, _impl_.faces_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::DetectFacesResponse_Face>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void DetectFacesResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:DetectFacesResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.faces_.Clear();
  _impl_.status_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DetectFacesResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DetectFacesResponse& this_ = static_cast<const DetectFacesResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DetectFacesResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DetectFacesResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:DetectFacesResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .DetectFaceStatus.Enum status = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_status(), target);
    }
  }

  // repeated .DetectFacesResponse.Face faces = 2;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_faces_size());
       i < n; i++) {
    const auto& repfield = this_._internal_faces().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            2, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DetectFacesResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DetectFacesResponse::ByteSizeLong(const MessageLite& base) {
  const DetectFacesResponse& this_ = static_cast<const DetectFacesResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DetectFacesResponse::ByteSizeLong() const {
  const DetectFacesResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:DetectFacesResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .DetectFacesResponse.Face faces = 2;
    {
      total_size += 1UL * this_._internal_faces_size();
      for (const auto& msg : this_._internal_faces()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
   {
    // .DetectFaceStatus.Enum status = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void DetectFacesResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DetectFacesResponse*>(&to_msg);
  auto& from = static_cast<const DetectFacesResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DetectFacesResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_faces()->MergeFrom(
      from._internal_faces());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_status() != 0) {
      _this->_impl_.status_ = from._impl_.status_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DetectFacesResponse::CopyFrom(const DetectFacesResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DetectFacesResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DetectFacesResponse::InternalSwap(DetectFacesResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.faces_.InternalSwap(&other->_impl_.faces_);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata DetectFacesResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DetectFaceStatus::_Internal {
 public:
};

DetectFaceStatus::DetectFaceStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, DetectFaceStatus_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:DetectFaceStatus)
}
DetectFaceStatus::DetectFaceStatus(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DetectFaceStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, DetectFaceStatus_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DetectFaceStatus* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:DetectFaceStatus)
}

inline void* PROTOBUF_NONNULL DetectFaceStatus::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DetectFaceStatus(arena);
}
constexpr auto DetectFaceStatus::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DetectFaceStatus),
                                            alignof(DetectFaceStatus));
}
constexpr auto DetectFaceStatus::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_DetectFaceStatus_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DetectFaceStatus::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<DetectFaceStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DetectFaceStatus::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<DetectFaceStatus>(), &DetectFaceStatus::ByteSizeLong,
              &DetectFaceStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DetectFaceStatus, _impl_._cached_size_),
          false,
      },
      &DetectFaceStatus::kDescriptorMethods,
      &descriptor_table_service_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull DetectFaceStatus_class_data_ =
        DetectFaceStatus::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
DetectFaceStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&DetectFaceStatus_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(DetectFaceStatus_class_data_.tc_table);
  return DetectFaceStatus_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
DetectFaceStatus::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    DetectFaceStatus_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DetectFaceStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata DetectFaceStatus::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_service_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
